=== ProcessEight/m23-example-modules/htdocs/app/code/DevCertUnitOne/OneThree/etc/warehouses_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Process Eight
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact ProcessEight for more information.
 *
 * @package     m23-example-modules
 * @copyright   Copyright (c) 2019 Process Eight
 * @author      Process Eight
 *
 */
 -->
<!--
Example XSD Schema file which defines our custom config XML.
The file is used to validate the warehouse_list.xml config file.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="warehouses_list" type="warehousesList"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="warehousesList">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="warehouse" type="warehouseType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="warehouseType">
        <xs:sequence>
            <xs:element name="name"/>
            <xs:element name="postcode"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ProcessEight/m23-example-modules/htdocs/app/code/DevCertUnitOne/OneThree/etc/warehouses_list.xml
<?xml version="1.0"?>
<!--
/**
 * Process Eight
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact ProcessEight for more information.
 *
 * @package     m23-example-modules
 * @copyright   Copyright (c) 2019 Process Eight
 * @author      Process Eight
 *
 */
 -->
<!--
 Example config file which defines custom config values.
 The file is validated by the warehouses_list.xsd schema.
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:DevCertUnitOne_OneThree:etc/warehouses_list.xsd">
    <warehouses_list>
        <warehouse>
            <name>North</name>
            <postcode>AB12 9DE</postcode>
        </warehouse>
        <warehouse>
            <name>South</name>
            <postcode>FG34 8HJ</postcode>
        </warehouse>
    </warehouses_list>
</config>
